# Generated by Django 5.0.1 on 2024-01-29 03:13

import copyformat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_doc",
                    models.FileField(
                        upload_to="originals/",
                        validators=[copyformat.models.validate_docx_file],
                    ),
                ),
                (
                    "translated_doc",
                    models.FileField(
                        upload_to="translations/",
                        validators=[copyformat.models.validate_docx_file],
                    ),
                ),
            ],
        ),
    ]
